name: "ClaimFly"
version: "${project.version}"
author: "Trophonix"
main: "com.trophonix.claimfly.ClaimFly"
api-version: "1.13"
softdepend: [Essentials, CMI, GriefPrevention, Residence]
commands:
  claimfly:
    description: "Admin config commands"
    permission: "claimfly.admin"
permissions:
  claimfly.admin:
    description: "ClaimFly admin command"
  claimfly.bypass:
    description: "Bypass flight restrictions"
  gpfly.admin:
    children: [claimfly.admin]
  gpfly.bypass:
    children: [claimfly.bypass]